baseURL: "https://wingstofly.vercel.app"
languageCode: "en-us"
title: "MYSURU TOURISM "

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
params:
  favicon: "/assets/images/Wings.svg"
  copyright: "2020"

  # Navbar Menus
  customMenusleft:
    - name: "About"
      Url: "/about"
    - name: "Contact us"
      Url: "/contact"
    - name: "Updates"
      Url: "/news"
    - name: "COVID-19"
      Url: "/healthcare"
    - name: "Women Employment"
      Url: "/employment"
    - name: "Places"
      Url: "/places"  
  customMenus:
    


  #home
  home:
    bigline: "MYSURU TOURISM"
    Tagline: "LOVE ALL , SERVE ALL "
    button: "Journey Begins"
    buttonlink: "#these-things"

  #Here we do
  description:
    heading: "WELCOME KARNATAKA"

    des:    "provide you the best journey to keep your mind peaceful.The old city of Mysore was built around the main palace of the Wodeyar dynasty. Many mansions and smaller palaces were built for close relatives of the rulers in urban districts such as Nazarbad, and Lakshipuram. By contrast the agraharas (residential areas) consisted of mall houses, in these lived the palace cooks and clerks, who were mainly Brahmins."

  #these-things
  learn:
    heading: "Places you want to visit !!!"
    des: "We are provide the best hotels and rooms for the travellers."
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6NleS65ACeuQ9AgdhS5_PF4ZRw9rTPz8zJw&usqp=CAU"
    link: "/places"
    name: "Place"
  healthcare:
    heading: "Take an Story"
    des: "We are give an brief history of an temple, park, zoo."
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuOgiId4sFa9EjLpyQAWTKCMfTlqQgJe6w2Q&usqp=CAU"
    link: "/places"
    name: "Place"
  employment:
    heading: "Enjoy a great ride"
    des: "Good people can make a better ride (GOD)."
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStLSSmc29MFMFQj3swrXQ31ioUxPPP2_yjRQ&usqp=CAU"
    link: "/places"
    name: "Place"

  #Social
  social:
    facebook: "https://facebook.com"
    twitter: "https://twitter.com"
    instagram: "https://instagram.com"
